---
- name: Create application directory and copy source files
  hosts: ec2-hosts
  become: yes
  vars:
    app_dir: /opt/react-springboot-app

  tasks:

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Copy .env file
      ansible.builtin.copy:
        src: .env
        dest: "{{ app_dir }}/.env"
        mode: '0644'

    
