name: Deploy to DockerHub Registry Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 


      - name: Install frontend dependencies
        run: |
          cd react-app
          npm ci
      - name: Build frontend
        run: |
          cd react-app
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Build backend
        run: |
          cd springboot-app
          mvn clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-app:latest
          file: ./Dockerfile  
          
          

