name: Deploy to DockerHub Registry Pipeline

on:
  push:
    branches:
      - main  # ή το branch που θέλεις να κάνει deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # ή όποια έκδοση χρησιμοποιείς


      - name: Install frontend dependencies
        run: |
          cd react-app
          npm ci
      - name: Build frontend
        run: |
          cd react-app
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Build backend
        run: |
          cd springboot-app
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/full-stack-simple-app:latest"
          docker compose -f docker-compose.yml build
          docker tag full-stack-simple-app:latest $IMAGE_NAME
          docker push $IMAGE_NAME
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
        

